# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=90, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('circ', models.SmallIntegerField(default=1196)),
            ],
        ),
    ]
